from __future__ import annotations

from typing import Callable, Protocol, runtime_checkable


@runtime_checkable
class TitanBackend(Protocol):
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def status(self) -> dict: ...
    def get_positions(self) -> list[dict]: ...
    def get_closed_positions(self, limit: int = 200) -> list[dict]: ...
    def get_signals(self, min_score: float = 0.0) -> list[dict]: ...
    def get_signal_history(self, limit: int = 200, min_score: float = 0.0, cid: str | None = None) -> list[dict]: ...
    def get_rejects(self) -> list[str]: ...
    def get_alerts(self) -> list[dict]: ...
    def get_whales(self) -> list[dict]: ...
    def get_pnl_summary(self) -> dict: ...
    def get_trade_history(self) -> list[dict]: ...
    def get_config(self) -> dict: ...
    def get_logs(self, lines: int = 200) -> str: ...
    def get_snapshot(self, compressed: bool = True) -> str: ...
    def force_cycle(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def update_config(self, patch: dict) -> dict: ...
    def subscribe(self, event: str, callback: Callable) -> None: ...
    def unsubscribe(self, event: str, callback: Callable) -> None: ...
