from __future__ import annotations

from typing import TYPE_CHECKING, Callable, Protocol, runtime_checkable

if TYPE_CHECKING:
    from titan_signals import SignalDict
    from titan_types import (
        AlertDict, ErrorDict, PositionBriefDict, WhaleDict,
        PnlSummaryDict, TradeStatsDict, PortfolioOverviewDict, TradeRecordDict,
    )


@runtime_checkable
class TitanBackend(Protocol):
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def status(self) -> dict: ...
    def get_positions(self, brief: bool = True) -> list[PositionBriefDict]: ...
    def get_closed_positions(self, limit: int = 200) -> list[TradeRecordDict]: ...
    def get_signals(self, min_score: float = 0.0) -> list[SignalDict]: ...
    def get_signal_history(self, limit: int = 200, min_score: float = 0.0, cid: str | None = None) -> list[SignalDict]: ...
    def get_rejects(self) -> list[str]: ...
    def get_alerts(self) -> list[AlertDict]: ...
    def get_whales(self) -> list[WhaleDict]: ...
    def get_pnl_summary(self) -> PnlSummaryDict: ...
    def get_trade_stats(self) -> TradeStatsDict: ...
    def get_portfolio_overview(self) -> PortfolioOverviewDict: ...
    def get_recent_errors(self, limit: int = 20) -> list[ErrorDict]: ...
    def get_trade_history(self) -> list[TradeRecordDict]: ...
    def get_config(self) -> dict: ...
    def get_logs(self, lines: int = 200) -> str: ...
    def get_snapshot(self, compressed: bool = True) -> str: ...
    def force_cycle(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def update_config(self, patch: dict) -> dict: ...
    def subscribe(self, event: str, callback: Callable) -> None: ...
    def unsubscribe(self, event: str, callback: Callable) -> None: ...
